name = "GnuplotSimple"
uuid = "40ffc0fb-4131-4de7-ada6-8152e65c705a"
authors = ["Tyler Beason <tbeas12@gmail.com>"]
version = "0.1.0"

[deps]
Gnuplot = "dc211083-a33a-5b79-959f-2ff34033469d"

[compat]
julia = "^1.1"
Gnuplot = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
